five_axis_robot:
   # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

     # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: a_axis_servo_to_a_axis_horn
    # pid: {p: 100.0, i: 0.001, d: 10.0}

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: c_axis_servo_to_c_axis_horn
  #   pid: {p: 100.0, i: 0.001, d: 10.0}

dynamixel_control:
  serial_interface: /dev/ttyACM0
  loop_frequency: 1000
  cycle_time_error_threshold: 0.3
  baudrate: 1000000 # in bauds
  read_timeout: 0.01 # in seconds
  scan_timeout: 0.02 # in seconds
  # Configuration of the servos
  servos:
    a_axis_servo_to_a_axis_horn:
    # hardware ID of the actuator
      id: 1
      # offset to be added, in radians, to the position of an actuator
      # offset: 3.14159265359 # in rad
      # # max joint speed
      # # it shoud NOT be used for actuators in velocity mode
      # max_speed: 0.1 # in rad/s

    c_axis_servo_to_c_axis_horn:
      id: 2
      # offset: 3.14159265359
      # command mode for the joint, either position or velocity
      #command_interface: position

  # default mode
  default_command_interface: position